# Generated by Django 5.2.4 on 2025-07-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Listing', '0012_alter_listingmodel_country_alter_listingmodel_price_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Listing.listingmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review_message', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Listing.listingmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
