# Generated by Django 5.2.4 on 2025-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review_And_Ratings', '0002_alter_propertyratingmodel_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyratingmodel',
            name='rating',
            field=models.FloatField(choices=[(5.0, '5'), (4.5, '4.5'), (4.0, '4'), (3.5, '3.5'), (3.0, '3'), (2.5, '2.5'), (2.0, '2'), (1.5, '1.5'), (1.0, '1')], null=True),
        ),
        migrations.AlterField(
            model_name='propertyreviewmodel',
            name='review_message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertyreviewmodel',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
