# Generated by Django 5.2.4 on 2025-08-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review_And_Ratings', '0003_alter_propertyratingmodel_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyreviewmodel',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='propertyreviewmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='propertyreviewmodel',
            name='subject',
        ),
    ]
