# Generated by Django 5.2 on 2025-05-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0003_alter_listing_bathrooms_alter_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
