# Generated by Django 5.2 on 2025-05-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0004_listing_property_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listing',
            new_name='ListingModel',
        ),
    ]
