# Generated by Django 5.2 on 2025-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0006_listingmodel_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='available',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='balcony',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='bank_debt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='city_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='kitchens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='ownership_documents',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property_landarea',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='zipcode',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
