# Generated by Django 5.2 on 2025-06-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0007_remove_listingmodel_available_listingmodel_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='country',
            field=models.CharField(choices=[('Ethiopia', 'Ethiopia')], max_length=255, null=True),
        ),
    ]
