# Generated by Django 5.2 on 2025-06-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0008_alter_listingmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='country',
            field=models.CharField(choices=[('ETH', 'Ethiopia'), ('KEN', 'Kenya')], default='ETH', max_length=3),
        ),
    ]
