# Generated by Django 5.2 on 2025-06-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0009_alter_listingmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='bank_debt',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='furnished',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='ownership_documents',
            field=models.CharField(choices=[('Digital Certificate of Land Ownership', 'Digital Certificate of Land Ownership'), ('Lease Ownership', 'Lease Ownership'), ('Cadester Ownership', 'Cadester Ownership')], default='Digital Certificate of Land Ownership', max_length=255),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='parking',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=155),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='property_condition',
            field=models.CharField(choices=[('Newly Built', 'Newly Built'), ('!0+ Years Ago', '10+ Years Ago')], default='!0+ Years Ago', max_length=255),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='property_status',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], default='For Rent', max_length=255),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Bare Land', 'Bare Land'), ('Business Shop', 'Business Shop'), ('Commercial Land', 'Commercial Land'), ('Condominium', 'Condominium'), ('Land for Plot', 'Land for Plot'), ('Office', 'Office'), ('Studio', 'Studio'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa')], default='Apartment', max_length=50),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='province',
            field=models.CharField(choices=[('Addis Abeba', 'Addis Abeba'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul Gumuz', 'Benishangul Gumuz'), ('Central Ethiopia', 'Central Ethiopia'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Sidama', 'Sidama'), ('Somali Region', 'Somali Region'), ('South Ethiopia', 'South Ethiopia'), ('South West Ethiopia', 'South West Ethiopia'), ('Tigray', 'Tigray')], default='Addis Abeba', max_length=255),
        ),
    ]
