# Generated by Django 5.2 on 2025-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0010_alter_listingmodel_bank_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
