# Generated by Django 5.2.4 on 2025-07-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0011_listingmodel_latitude_listingmodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='country',
            field=models.CharField(choices=[('ETHIOPIA', 'Ethiopia'), ('KENYA', 'Kenya')], default='ETHIOPIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='property_condition',
            field=models.CharField(choices=[('Newly Built', 'Newly Built'), ('10+ Years Ago', '10+ Years Ago')], default='10+ Years Ago', max_length=255),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
