# Generated by Django 5.2.4 on 2025-07-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0012_alter_listingmodel_country_alter_listingmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='longitude',
        ),
    ]
