# Generated by Django 5.2.4 on 2025-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0013_remove_listingmodel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
